### ISSUE TITLE
README and project information

### ISSUE THREAD

**Issue by Dahie** [nlhans/MAS2Extract#1]
Hey

Interesting project, I'm a bit annoyed ISI never releases a full specification of the MAS file format, but I guess they don't have one either.

Anyway, can you add a readme to the project regarding its state? Is it a prototype, is it working? What features of the MAS (and what variants of the format for which games) are supported?
And maybe some license information for using with OpenSource would be appreciated. Thanks :)

**Comment by nlhans** [comment]
Hi Daniel,

I totally agree. ISI opens their game for modding , but in the end technical support can be disappointing. That's why I made this utility ;) . They really should step up their community game and work on better formats, and also more telemetry data on their internal plugins. Anyway, that's probably a rant for another topic.

I've updated the project with some better documentation, cleaned up the code and added a README+license. 

As a direct answer on your questions:
- I made this class for my telemetry program (SimTelemetry), but as rFactor 2 has a lack of content (well when I last looked it did, but that's over 7 months ago) I'm not very focussed on this sim atm. Currently I'm working on my telemetry tool to be ready to support multiple sims.
  I do plan to keep this format up to date if there are any changes, because it's quite fundamental for SimTelemetry to work. It works fine with the tracks and mods I currently have installed.
- It's not a prototype, it can read the MAS2 files and extract it's contents to a file or to memory in string (for INI files) or byte array format.

In fact, I've built a mod viewer already using this class for viewing cars/mods, their engine curves, etc. 
https://dl.dropbox.com/u/207647/Big%20icons.png
https://dl.dropbox.com/u/207647/Post_5.png
(WIP)
- I it will not work for other games like original rFactor, because there is no auto-detect version. It only detects whether it is reading GMOTOR MAS 2.90 (which is the one rFactor 2 is using).
  However it may  work on rFmod files if you fiddle with the file header detection (I believe it doesn't use the MAS string but some other - completely irrelevant for getting the data though).

I may work on a more generic tool some time, which also has support for Simraceway, rFactor, GTR2, etc. 

Please let me know if you need to know anything else or (technical) support on this tool

**Comment by Dahie** [comment]
Thanks for the detailed answer. That was all I needed to know for know. :)

I played with a few ideas in my head what could be done with a MAS-library some time ago, but wasn't in a mood to reverse engineer it. It's nice to know other people take the time. C# is not my language, but based on you implementation, other libs for other languages shouldn't be a problem. :)

Simracing needs more programmers 8)

**Comment by nlhans** [comment]
Java or C#, it's just a choice of flavor. ;) I am not making heavy use of .NET or language structure dependent stuff, so it should be very easy to port to Java or a similar language.
You maybe have to find an alternative gzip/deflate (Zlib?) library, but I am sure there is some out there for Java.

Reverse engineering such things can be quite troublesome indeed. That's why I made it open source, so others don't have to go through the same hell. I am interested to see what you will be building with the lib. If you want, keep me posted.
